/* Emberdeep browser interface. No network or third-party runtime required. */
(() => {
  'use strict';
  const E=window.EmberEngine, $=id=>document.getElementById(id), SAVE='emberdeep.expedition.v1';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let game=E.createGame(),selected=0,action='attack',walking=null,sound=false,audio=null,storage=true,lastLog='';
  try{const raw=localStorage.getItem(SAVE);if(raw){const loaded=E.migrateSave(JSON.parse(raw));if(E.validateSave(loaded)){game=loaded;E.reveal(game);}}}catch{storage=false;}
  const canvas=$('map'),ctx=canvas.getContext('2d');
  const icons={warden:'♜',ranger:'♞',arcanist:'♝'},enemyIcons={rat:'♟',sword:'⚔',shield:'♜',spark:'♝',crown:'♛'};
  function save(){try{localStorage.setItem(SAVE,JSON.stringify(game));$('save-status').textContent='SAVED ON THIS DEVICE';}catch{storage=false;$('save-status').textContent='SAVING UNAVAILABLE · KEEP THIS TAB OPEN';}}
  function drawMap(){const tile=28;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#0d130f';ctx.fillRect(0,0,canvas.width,canvas.height);const seen=new Set(game.map.seen),visible=new Set(game.map.visible);for(let y=0;y<E.H;y++)for(let x=0;x<E.W;x++){const k=E.key(x,y),isSeen=seen.has(k),lit=visible.has(k),floor=game.map.tiles[y][x];if(!isSeen){if((x+y)%3===0){ctx.fillStyle='#1b251a55';ctx.fillRect(x*tile+13,y*tile+13,1,1);}continue;}const d=Math.hypot(x-game.pos.x,y-game.pos.y),variation=((x*7+y*13)%9);if(floor){const b=lit?Math.max(31,55-Math.floor(d*2))+variation:23;ctx.fillStyle=`rgb(${b},${b+6},${b-3})`;ctx.fillRect(x*tile+1,y*tile+1,tile-2,tile-2);ctx.strokeStyle=lit?'#74816216':'#5363460c';ctx.strokeRect(x*tile+2.5,y*tile+2.5,tile-5,tile-5);if((x*19+y*7)%11===0){ctx.strokeStyle=lit?'#17251266':'#10190e66';ctx.beginPath();ctx.moveTo(x*tile+6,y*tile+4);ctx.lineTo(x*tile+10,y*tile+13);ctx.lineTo(x*tile+8,y*tile+18);ctx.stroke();}}else{ctx.fillStyle=lit?'#48513a':'#242d21';ctx.fillRect(x*tile,y*tile,tile,tile);ctx.fillStyle=lit?'#5a6247':'#2b3527';ctx.fillRect(x*tile+1,y*tile+1,tile-2,3);ctx.fillStyle='#10190d66';ctx.fillRect(x*tile,y*tile+tile-4,tile,4);ctx.strokeStyle='#1a251577';ctx.strokeRect(x*tile+.5,y*tile+.5,tile-1,tile-1);}}
    const glow=ctx.createRadialGradient((game.pos.x+.5)*tile,(game.pos.y+.5)*tile,5,(game.pos.x+.5)*tile,(game.pos.y+.5)*tile,140);glow.addColorStop(0,'#d3a5471b');glow.addColorStop(1,'#d3a54700');ctx.fillStyle=glow;ctx.fillRect(0,0,canvas.width,canvas.height);
    for(const e of game.map.entities){if(!seen.has(E.key(e.x,e.y)))continue;const lit=visible.has(E.key(e.x,e.y));ctx.globalAlpha=lit?1:.35;const x=(e.x+.5)*tile,y=(e.y+.5)*tile;let color='#c4aa77',glyph='◆';if(e.type==='enemy'){color='#d18d6e';glyph='⚔';}if(e.type==='boss'){color='#e1a26c';glyph='♛';}if(e.type==='shrine'){color='#9ac3bf';glyph='✦';}if(e.type==='stairs'){color='#c5c9af';glyph='≋';}ctx.shadowColor=color;ctx.shadowBlur=lit?10:0;ctx.fillStyle=color;ctx.font=`${e.type==='chest'?18:24}px Georgia`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(glyph,x,y+1);ctx.shadowBlur=0;ctx.globalAlpha=1;}
    const px=(game.pos.x+.5)*tile,py=(game.pos.y+.5)*tile;ctx.fillStyle='#d9bd80';ctx.strokeStyle='#edd9a4';ctx.lineWidth=1.5;ctx.shadowColor='#e7b34d';ctx.shadowBlur=17;ctx.beginPath();ctx.moveTo(px,py-10);ctx.lineTo(px+7,py);ctx.lineTo(px,py+10);ctx.lineTo(px-7,py);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#c5b38177';ctx.lineWidth=1;ctx.beginPath();ctx.arc(px,py,15,0,Math.PI*2);ctx.stroke();
    let floorSeen=0,total=0;game.map.tiles.forEach((row,y)=>row.forEach((t,x)=>{if(t){total++;if(seen.has(E.key(x,y)))floorSeen++;}}));$('explored').textContent=`${Math.round(floorSeen/total*100)}% EXPLORED · SEED ${game.seed.slice(0,16).toUpperCase()}`;$('coordinates').textContent=`${String(game.pos.x).padStart(2,'0')} : ${String(game.pos.y).padStart(2,'0')}  /  TORCHLIT PASSAGE`;canvas.setAttribute('aria-label',`Dungeon map, floor ${game.floor}. Party at column ${game.pos.x}, row ${game.pos.y}. ${E.DIRS.map(([dx,dy],i)=>`${['North','east','south','west'][i]}: ${game.map.tiles[game.pos.y+dy]?.[game.pos.x+dx]===1?'open':'wall'}`).join('. ')}. Use arrow keys or WASD to move.`);
  }
  function render(){
    const inTown=game.phase==='town';
    $('town').hidden=!inTown;
    document.querySelector('.dungeon-section').hidden=inTown;
    document.querySelector('.controls-hint').hidden=inTown;
    if(inTown)$('touch-controls').hidden=true;
    $('town-btn').hidden=inTown;
    $('town-btn').disabled=game.phase==='combat';
    $('town-btn').title=game.phase==='combat'?'Finish the encounter before returning to town.':'Return with your recovered treasure and campaign progress.';
    $('journey-label').textContent=inTown?'BETWEEN EXPEDITIONS':'THE DESCENT';
    $('floor-title').textContent=inTown?'Hearthglen':E.FLOORS[game.floor-1];
    $('floor-label').textContent=inTown?`${game.victories} DUNGEONS CLEARED`:`DEPTH 0${game.floor} OF 03 · ${E.DIFFICULTIES[game.difficulty].name.toUpperCase()}`;
    $('gold').textContent=game.gold;$('potions').textContent=game.potions;$('turn').textContent=inTown?game.xp:game.turn;
    $('third-resource-label').textContent=inTown?'TRAINING XP':'TURNS';
    $('party-level').textContent=`AVG LVL ${game.level}`;
    $('seed-label').textContent=inTown?`${game.xp} TRAINING XP · ${E.treasureValue(game)} GOLD IN TREASURE`:`DUNGEON SEED: ${game.seed}`;
    $('mode-label').textContent=game.phase==='combat'?`COMBAT · ROUND ${game.combat.round}`:game.phase==='won'?'EMBERHEART RECLAIMED':game.phase==='lost'?'EXPEDITION ENDED':'EXPLORATION';
    $('objective').textContent=inTown?'A warm hearth, a fair trade, and the promise of another adventure.':game.floor<3?'Find the stairwell. Keep your party alive. The Emberheart awaits below.':'Find the Ash Warden. Reclaim the Emberheart. Bring everyone home.';
    $('quest-text').textContent=inTown?`${game.expeditions} expeditions · ${game.victories} victories. Choose a difficulty on the expedition board when your fellowship is ready.`:`${E.DIFFICULTIES[game.difficulty].name} difficulty. ${game.xp} shared training XP and ${E.treasureValue(game)} gold in unsold treasure. Return to town to spend your spoils.`;
    for(let i=1;i<=3;i++)$('depth-'+i).className=inTown?'':i===game.floor?'active':i<game.floor?'complete':'';
    renderParty();
    if(inTown)window.EmberTown.render(game,selected);
    else {drawMap();renderEncounter();renderActions();}
    renderLog();save();
  }
  function renderParty(){ $('party-hint').textContent=game.phase==='combat'?(action==='potion'?'Select a living ally to heal.':'Select an adventurer to take their turn.'):game.phase==='town'?'Select a hero for equipment, training, or a roster swap.':'Three souls. One way forward.';$('party').innerHTML=game.party.map((h,i)=>{const pct=h.hp/h.maxHp*100;return `<button class="hero-card ${h.id} ${selected===i?'selected':''} ${h.hp<=0?'fallen':''} ${game.phase==='combat'&&h.acted?'acted':''} ${action==='potion'&&h.hp>0&&h.hp<h.maxHp?'heal-target':''}" data-hero="${i}" aria-label="${h.name}, ${h.role}, ${h.hp} of ${h.maxHp} health${h.acted?', action used':''}" aria-pressed="${selected===i}"><span class="portrait" aria-hidden="true">${icons[h.id]}</span><span class="hero-info"><span class="hero-top"><strong>${h.name}</strong><span class="hero-number">0${i+1}</span></span><span class="hero-role">${h.role}</span><span class="hp-label"><span>${h.hp<=0?'FALLEN':'HEALTH'}</span><span>${h.hp} / ${h.maxHp}</span></span><div class="hp-track"><div class="hp-fill" style="width:${pct}%;${pct<30?'background:#be826b':''}"></div></div></span><span class="hero-meta"><span>⚔ ${h.attack} ATK · ${h.armor} ARM · LVL ${h.level}</span><span>${h.hp<=0?'Needs revival':game.phase==='combat'&&h.acted?'✓ Action taken':h.cooldown>0?'Special recharging':h.depthBonus?`Resolve +${h.depthBonus}`:'● Ready'}</span></span></button>`;}).join(''); }
  function renderLog(){const signature=JSON.stringify(game.log);if(signature===lastLog)return;lastLog=signature;$('log').innerHTML=game.log.slice(-20).map(l=>`<div class="log-entry ${['loot','danger','heal','combat','damage'].includes(l.type)?l.type:'info'}"><span class="log-turn">${String(l.turn).padStart(3,'0')}</span><span>${esc(l.text)}</span></div>`).join('');$('log').scrollTop=$('log').scrollHeight;}
  function renderEncounter(){ $('encounter').hidden=game.phase!=='combat';$('ending').hidden=!['won','lost'].includes(game.phase);if(game.phase==='combat'){const c=game.combat;$('encounter').innerHTML=`<div class="eyebrow">${c.boss?'THE FINAL GUARDIAN':'A SHADOW STIRS'}</div><h2>${c.boss?'The Ember Throne':'You are not alone.'}</h2><p class="encounter-sub">Round ${c.round} · ${game.party.filter(h=>h.hp>0&&!h.acted).length} adventurer actions remaining</p><div class="enemy-row">${c.enemies.map((e,i)=>{const intent=e.intent;const who=game.party[intent.target];const text=intent.type==='charge'?'◌ Gathering embers':intent.type==='all'?`⚠ ${intent.damage} base damage to everyone`:`↘ ${intent.damage} base damage → ${who?.hp>0?who.name:game.party.find(h=>h.hp>0)?.name||'party'}`;return `<button class="enemy-card ${e.type==='boss'?'boss':''} ${e.hp<=0?'defeated':''} ${['attack','special'].includes(action)?'targetable':''}" data-enemy="${i}" ${e.hp<=0?'disabled':''} aria-label="Target ${esc(e.name)}, ${e.hp} health. ${text}"><span class="enemy-glyph" aria-hidden="true">${enemyIcons[e.icon]||'♟'}</span><span class="enemy-name">${esc(e.name)}</span><span class="enemy-hp">${e.hp} / ${e.maxHp} HP ${e.marked>0?'· MARKED':''}</span><div class="hp-track"><div class="hp-fill" style="width:${e.hp/e.maxHp*100}%"></div></div><div class="enemy-intent">${e.hp>0?text:'Defeated'}</div><div class="enemy-armor">${e.armor?`${e.armor} armor · absorbs damage`:'No armor'}</div></button>`;}).join('')}</div><div class="battle-status">${c.guard?'♜ Bulwark active · incoming damage halved':action==='potion'?'Select a party member to restore 18 health.':`Choose a target for ${game.party[selected].name}’s ${action==='special'?'Hunter’s Mark':'attack'}.`}</div>`;}
    if(['won','lost'].includes(game.phase)){const won=game.phase==='won';$('ending').innerHTML=`<div class="ending-rune">${won?'✦':'♜'}</div><span class="eyebrow">${won?'THE LIGHT RETURNS':'THE TORCH GOES DARK'}</span><h2>${won?'An ember worth saving.':'Lost to the deep.'}</h2><p>${won?'The Ash Warden falls. Your fellowship carries the Emberheart back toward the surface. For the first time in an age, the halls are quiet.':'Your fellowship made its stand in the dark. Rescuers will bring everyone back to the inn with your recovered spoils and progress intact.'}</p><div class="ending-stats">DEPTH ${game.floor} · ${game.kills} FOES VANQUISHED · ${game.gold} GOLD</div><button class="primary-btn" data-return-town>Return to Hearthglen</button>`;}}
  function renderActions(){const node=$('actions');node.classList.toggle('combat-actions',game.phase==='combat');if(game.phase==='combat'){const h=game.party[selected],names={warden:['Bulwark','Halve all incoming damage'],ranger:['Hunter’s Mark','Strike + empower 2 hits'],arcanist:['Ember Wave',`${h.attack+1} damage to all enemies`]},special=names[h.id];node.innerHTML=`<div class="combat-action-head"><div><h3>${h.name}’s turn</h3><p>${E.equippedWeapon(h).name} · ${h.weaponGrip} ${h.weaponGrip===1?'hand':'hands'}</p></div><button class="quiet-btn" data-end>End round →</button></div><div class="combat-buttons"><button class="ability-btn ${action==='attack'?'active':''}" data-action="attack" ${h.acted?'disabled':''}><strong>⚔ ${E.weaponAttack(h).action}</strong><small>${h.attack} damage · ${E.damageText(E.weaponAttack(h).damage)}</small></button><button class="ability-btn ${action==='special'?'active':''}" data-action="special" ${h.acted||h.cooldown?'disabled':''}><strong>✧ ${special[0]}</strong><small>${h.cooldown?'Ready next round':special[1]}</small></button><button class="ability-btn ${action==='potion'?'active':''}" data-action="potion" ${h.acted||!game.potions||game.party.every(p=>p.hp<=0||p.hp===p.maxHp)?'disabled':''}><strong>♜ Healing Draught</strong><small>Restore 18 HP · ${game.potions} left</small></button><button class="ability-btn" data-action="guard" ${h.acted?'disabled':''}><strong>◇ Hold</strong><small>Skip this hero’s action</small></button></div>`;return;}const e=E.entityAt(game);let title='Follow the torchlight',copy='Explore the halls, gather supplies, and find a path into the deep.',button='',symbol='✧';if(e?.type==='stairs'){title='A stairwell into the unknown';copy='Gain resolve for this expedition (+5 max HP, +1 attack) and restore 12 health.';button='<button class="primary-btn" data-interact>Descend · Space ↓</button>';symbol='≋';}else if(e?.type==='shrine'){title='A moment of sanctuary';copy='Invoke the shrine once to heal and revive your entire party by 18 HP.';button='<button class="primary-btn" data-interact>Invoke shrine · Space</button>';symbol='✦';}else if(game.phase==='explore'){button=`<button class="secondary-btn" data-explore-heal ${game.potions===0||game.party.every(h=>h.hp<=0||h.hp===h.maxHp)?'disabled':''}>${action==='potion'?'Cancel healing':'Use draught'}</button>`;if(action==='potion'){title='Choose an adventurer';copy='Select a living party member to restore 18 health.';}}else{title=game.phase==='won'?'The Emberheart is yours':'Every ending is a beginning';copy='Return to town to sell treasure, train, and prepare your next expedition.';}node.innerHTML=`<div class="action-copy"><span class="action-symbol">${symbol}</span><div><h3>${title}</h3><p>${copy}</p></div></div>${button}`;}
  function stopWalking(){if(walking){clearInterval(walking);walking=null;}}
  function tone(kind='step'){if(!sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;oscillator.type=kind==='combat'?'triangle':'sine';oscillator.frequency.setValueAtTime(kind==='combat'?180:kind==='heal'?520:130,now);oscillator.frequency.exponentialRampToValueAtTime(kind==='heal'?780:70,now+.15);gain.gain.setValueAtTime(.035,now);gain.gain.exponentialRampToValueAtTime(.001,now+.2);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start();oscillator.stop(now+.21);}catch{sound=false;$('sound-btn').textContent='Sound unavailable';}}
  function afterAction(){if(game.phase==='combat'){const next=game.party.findIndex(h=>h.hp>0&&!h.acted);if(next>=0)selected=next;}else if(game.party[selected].hp<=0){selected=Math.max(0,game.party.findIndex(h=>h.hp>0));}action='attack';render();}
  function step(dx,dy){if(E.move(game,dx,dy)){tone(game.phase==='combat'?'combat':'step');afterAction();return true;}return false;}
  function perform(type,target=0){stopWalking();if(E.act(game,selected,type,target)){tone(type==='potion'?'heal':'combat');afterAction();return true;}return false;}
  function openNew(){stopWalking();$('new-dialog').showModal();}
  $('party').addEventListener('click',e=>{const button=e.target.closest('[data-hero]');if(!button)return;const i=Number(button.dataset.hero);if(action==='potion'){perform('potion',i);return;}if(game.party[i].hp<=0||game.phase==='combat'&&game.party[i].acted)return;selected=i;action='attack';render();});
  $('encounter').addEventListener('click',e=>{const button=e.target.closest('[data-enemy]');if(button&&['attack','special'].includes(action))perform(action,Number(button.dataset.enemy));});
  $('actions').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn||btn.disabled)return;if(btn.hasAttribute('data-interact')){stopWalking();if(E.interact(game)){tone('heal');afterAction();}}if(btn.hasAttribute('data-end')){if(E.endRound(game))afterAction();}if(btn.hasAttribute('data-explore-heal')){stopWalking();action=action==='potion'?'attack':'potion';render();}if(btn.dataset.action){const kind=btn.dataset.action;if(kind==='guard'||kind==='special'&&game.party[selected].id!=='ranger'){perform(kind);return;}action=kind;render();}});
  function returnHome(){stopWalking();if(E.returnToTown(game)){selected=0;action='attack';window.EmberTown.resetDraft();render();}}
  $('ending').addEventListener('click',e=>{if(e.target.closest('[data-return-town]'))returnHome();});
  $('town-btn').addEventListener('click',()=>{stopWalking();if(['won','lost'].includes(game.phase))returnHome();else if(game.phase==='explore')$('retreat-dialog').showModal();});
  $('confirm-retreat').addEventListener('click',()=>{$('retreat-dialog').close();returnHome();});
  $('town').addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||b.disabled||game.phase!=='town')return;
    const d=b.dataset;
    if(d.townTab){window.EmberTown.setTab(d.townTab);render();$('town').querySelector(`[data-town-tab="${d.townTab}"]`).focus();return;}
    if(d.armorLocation){
      if(!window.EmberTown.setArmorAttribute('location',d.armorLocation)||!window.EmberTown.setArmorAttribute('layer',d.armorLayer))return;
      const piece=E.EQUIPMENT[game.party[selected].gear.armor[d.armorLocation][d.armorLayer]];
      if(piece)for(const attribute of ['tier','weight','class'])window.EmberTown.setArmorAttribute(attribute,piece[attribute]);
      render();$('town').querySelector('[data-armor-filter="location"]').focus();return;
    }
    let changed=false;
    if(d.sell)changed=E.sellTreasure(game,d.sell);
    else if(d.buyGear)changed=E.buyEquipment(game,selected,d.buyGear);
    else if(d.ownedWeapon)changed=E.equipWeapon(game,selected,d.ownedWeapon==='starting'?null:d.ownedWeapon);
    else if(d.weaponGrip)changed=E.setWeaponGrip(game,selected,Number(d.weaponGrip));
    else if(d.ownedEquip)changed=E.equipArmor(game,selected,d.ownedEquip);
    else if(d.unequipLocation)changed=E.unequipArmor(game,selected,d.unequipLocation,d.unequipLayer);
    else if(b.hasAttribute('data-buy-potion'))changed=E.buyPotion(game);
    else if(d.recruit)changed=E.recruit(game,d.recruit);
    else if(d.swap)changed=E.swapParty(game,selected,d.swap);
    else if(d.train!==undefined)changed=E.train(game,Number(d.train));
    if(changed){action='attack';tone('heal');render();}
  });
  $('town').addEventListener('input',e=>{if(e.target.id==='dungeon-seed')window.EmberTown.setSeed(e.target.value);});
  $('town').addEventListener('change',e=>{
    if(e.target.dataset?.weaponFilter){if(window.EmberWeaponUI.setFilter(e.target.value)){render();$('town').querySelector('[data-weapon-filter="type"]').focus();}return;}
    if(e.target.dataset?.armorFilter){const attribute=e.target.dataset.armorFilter;if(window.EmberTown.setArmorAttribute(attribute,e.target.value)){render();$('town').querySelector(`[data-armor-filter="${attribute}"]`).focus();}return;}
    if(e.target.name==='difficulty'){window.EmberTown.setDifficulty(e.target.value);render();$('town').querySelector('input[name="difficulty"]:checked').focus();}
  });
  $('town').addEventListener('submit',e=>{if(e.target.id!=='depart-form')return;e.preventDefault();stopWalking();if(E.depart(game,window.EmberTown.options(game))){window.EmberTown.resetDraft();selected=0;action='attack';render();canvas.focus();}});
  canvas.addEventListener('click',e=>{if(game.phase!=='explore')return;stopWalking();const rect=canvas.getBoundingClientRect(),scale=Math.min(rect.width/canvas.width,rect.height/canvas.height),left=(rect.width-canvas.width*scale)/2,top=(rect.height-canvas.height*scale)/2;const x=Math.floor((e.clientX-rect.left-left)/(28*scale)),y=Math.floor((e.clientY-rect.top-top)/(28*scale)),path=E.pathTo(game,x,y);if(!path.length)return;let i=0;const tick=()=>{const p=path[i++];if(!p||game.phase!=='explore'){stopWalking();return;}const entity=E.entityAt(game,p.x,p.y);if(!step(p.x-game.pos.x,p.y-game.pos.y)||i>=path.length||entity)stopWalking();};walking=setInterval(tick,110);tick();});
  document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable||(e.target.tagName==='BUTTON'&&[' ','Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='?'){e.preventDefault();stopWalking();$('help-dialog').showModal();return;}if(e.key==='Escape'){stopWalking();action='attack';render();return;}const moves={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0],w:[0,-1],s:[0,1],a:[-1,0],d:[1,0]};if(game.phase==='explore'&&moves[e.key]){e.preventDefault();stopWalking();step(...moves[e.key]);}if(e.code==='Space'&&game.phase==='explore'){e.preventDefault();stopWalking();if(E.interact(game))afterAction();}if(['1','2','3'].includes(e.key)){const i=Number(e.key)-1;if(action==='potion'){perform('potion',i);return;}if(game.party[i].hp>0&&(!game.party[i].acted||game.phase!=='combat')){selected=i;action='attack';render();}}});
  $('help-btn').addEventListener('click',()=>{stopWalking();$('help-dialog').showModal();});$('restart-btn').addEventListener('click',openNew);document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
  $('new-form').addEventListener('submit',e=>{e.preventDefault();stopWalking();game=E.createGame();selected=0;action='attack';lastLog='';window.EmberTown.resetDraft();$('new-dialog').close();render();});
  $('sound-btn').addEventListener('click',()=>{sound=!sound;$('sound-btn').setAttribute('aria-pressed',String(sound));$('sound-btn').textContent=sound?'Sound on':'Sound off';tone('heal');});
  $('touch-toggle').addEventListener('click',()=>{const show=$('touch-controls').hidden;$('touch-controls').hidden=!show;$('touch-toggle').setAttribute('aria-expanded',String(show));});$('touch-controls').addEventListener('click',e=>{const b=e.target.closest('[data-move]');if(b){stopWalking();step(...b.dataset.move.split(',').map(Number));}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopWalking();});
  const illustration=document.createElement('img');illustration.src='assets/emberdeep.png';illustration.alt='Three adventurers carry a torch into the ancient vaults of Emberdeep.';illustration.className='expedition-art';document.querySelector('.objective-card').prepend(illustration);
  if(game.phase==='combat'){selected=Math.max(0,game.party.findIndex(h=>h.hp>0&&!h.acted));}else{selected=Math.max(0,game.party.findIndex(h=>h.hp>0));}render();
  // Optional browser-agent interface. The game works unchanged without WebMCP.
  const context=document.modelContext;
  if(context?.registerTool){
    const lifecycle=new AbortController();
    const armorSchema={type:'object',properties:{location:{type:'string',enum:Object.keys(E.ARMOR_LOCATIONS)},layer:{type:'string',enum:Object.keys(E.ARMOR_LAYERS)},tier:{type:'integer',minimum:1,maximum:5},weight:{type:'string',enum:Object.keys(E.ARMOR_WEIGHTS)},class:{type:'string',enum:Object.keys(E.ARMOR_CLASSES)}},required:['location','layer','tier','weight','class'],additionalProperties:false};
    const snapshot=()=>({phase:game.phase,difficulty:game.difficulty,gold:game.gold,xp:game.xp,treasures:{...game.treasures},reserves:game.reserves.map(h=>({...h})),floor:game.floor,position:{...game.pos},party:game.party.map(h=>({...h})),potions:game.potions,round:game.combat?.round||null,enemies:game.combat?.enemies.map(e=>({...e}))||[],nearby:game.map.entities.filter(e=>game.map.visible.includes(E.key(e.x,e.y))),message:game.message});
    const registrations=[
      {name:'read_expedition',title:'Read expedition',description:'Read party health, combat intentions, visible discoveries, and the current phase.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>snapshot()},
      {name:'move_party',title:'Move party',description:'Walk up to ten cardinal steps during exploration. Stops on encounters or discoveries.',inputSchema:{type:'object',properties:{directions:{type:'array',items:{type:'string',enum:['north','east','south','west']},minItems:1,maxItems:10}},required:['directions'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{const directions=input?.directions;if(!Array.isArray(directions)||!directions.length||directions.length>10||directions.some(d=>!['north','east','south','west'].includes(d)))throw Error('Provide 1–10 cardinal directions.');if(game.phase!=='explore')throw Error('Party movement requires exploration.');stopWalking();for(const d of directions){const [dx,dy]=E.DIRS[['north','east','south','west'].indexOf(d)];if(!step(dx,dy)||game.phase!=='explore'||E.entityAt(game))break;}return snapshot();}},
      {name:'take_hero_action',title:'Take hero action',description:'Execute one hero action in battle, or use a draught outside battle. Hero and target indices are zero-based. Potion targets are party members; attacks and Hunter’s Mark target enemies.',inputSchema:{type:'object',properties:{hero:{type:'integer',minimum:0,maximum:2},action:{type:'string',enum:['attack','special','potion','guard']},target:{type:'integer',minimum:0,maximum:2}},required:['hero','action','target'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!Number.isInteger(input?.hero)||input.hero<0||input.hero>2||!Number.isInteger(input.target)||input.target<0||input.target>2||!['attack','special','potion','guard'].includes(input.action))throw Error('Invalid hero action.');stopWalking();if(!E.act(game,input.hero,input.action,input.target))throw Error('That action is not available for this hero or target.');afterAction();return snapshot();}},
      {name:'use_current_discovery',title:'Use current discovery',description:'Invoke the shrine or descend the stairs on the party’s current tile.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{stopWalking();if(!E.interact(game))throw Error('Stand on an unused shrine or stairwell first.');afterAction();return snapshot();}},
      {name:'start_dungeon',title:'Enter a dungeon',description:'Depart from town with the current fellowship and a fixed difficulty. Preserves campaign progress.',inputSchema:{type:'object',properties:{difficulty:{type:'string',enum:Object.keys(E.DIFFICULTIES)},seed:{type:'string',maxLength:40}},required:['difficulty'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{
        if(!input||input.seed!==undefined&&typeof input.seed!=='string')throw Error('Provide a difficulty and an optional seed.');
        if(!E.depart(game,input))throw Error('Select a valid difficulty while in town.');
        stopWalking();selected=0;action='attack';window.EmberTown.resetDraft();render();return snapshot();
      }},
      {name:'use_town_service',title:'Use a town service',description:'Sell treasure, buy and equip gear, equip owned weapons or armor, set weapon grip, remove an armor layer, buy a draught, recruit, swap, or train. Requires town. Armor purchases only replace their own location and layer.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['sell','equipment','equip_owned','equip_weapon','weapon_grip','unequip_armor','potion','recruit','swap','train']},hero:{type:'integer',minimum:0,maximum:2},item:{type:['string','null']},grip:{type:'integer',enum:[1,2]},location:{type:'string',enum:Object.keys(E.ARMOR_LOCATIONS)},layer:{type:'string',enum:Object.keys(E.ARMOR_LAYERS)}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{
        if(game.phase!=='town'||!input)throw Error('Town services require returning to Hearthglen.');
        const operations={sell:()=>E.sellTreasure(game,input.item||'all'),equipment:()=>E.buyEquipment(game,input.hero,input.item),equip_owned:()=>E.equipArmor(game,input.hero,input.item),equip_weapon:()=>E.equipWeapon(game,input.hero,input.item,input.grip),weapon_grip:()=>E.setWeaponGrip(game,input.hero,input.grip),unequip_armor:()=>E.unequipArmor(game,input.hero,input.location,input.layer),potion:()=>E.buyPotion(game),recruit:()=>E.recruit(game,input.item),swap:()=>E.swapParty(game,input.hero,input.item),train:()=>E.train(game,input.hero)};
        if(!Object.hasOwn(operations,input.service)||!operations[input.service]())throw Error('This purchase or party action is unavailable; check funds, XP, targets, and ownership.');
        action='attack';render();return snapshot();
      }},
      {name:'read_town_catalog',title:'Read town catalog',description:'Read weapons, armor attribute choices, treasure, recruits, training, and difficulties. Supply all five armor attributes to look up one armor piece and its purchase ID.',inputSchema:{type:'object',properties:{armor:armorSchema},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:input=>{
        if(input?.armor!==undefined&&!E.validArmorAttributes(input.armor))throw Error('Armor needs valid independent location, layer, tier, weight, and class attributes.');
        const itemId=input?.armor?E.armorItemId(input.armor):null;
        return {weaponTypes:E.WEAPON_TYPES,weaponSizes:E.WEAPON_SIZES,startingWeapons:E.STARTING_WEAPONS,equipment:Object.fromEntries(Object.entries(E.EQUIPMENT).filter(([,item])=>item.slot==='weapon')),armorAttributes:{location:E.ARMOR_LOCATIONS,layer:E.ARMOR_LAYERS,tier:E.ARMOR_TIERS,weight:E.ARMOR_WEIGHTS,class:E.ARMOR_CLASSES},armorItem:itemId?{id:itemId,...E.EQUIPMENT[itemId]}:null,treasures:E.TREASURES,recruits:E.RECRUITS,difficulties:E.DIFFICULTIES,training:game.party.map(h=>({hero:h.uid,level:h.level,...E.trainingCost(h)}))};
      }},
      {name:'return_to_town',title:'Return to Hearthglen',description:'End the current dungeon and return to town, preserving spoils and campaign progress. Requires confirmRetreat=true during exploration; unavailable during combat.',inputSchema:{type:'object',properties:{confirmRetreat:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{
        if(game.phase==='explore'&&input?.confirmRetreat!==true)throw Error('Returning abandons this dungeon; confirm the retreat first.');
        if(!['explore','won','lost'].includes(game.phase))throw Error('Finish the encounter before returning, or you are already in town.');
        returnHome();return snapshot();
      }}
    ];
    for(const tool of registrations){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional capability; gameplay remains available. */}}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
