const {test}=require('node:test');
const assert=require('node:assert/strict');
const E=require('../engine.js');
function dungeonGame(seed){const g=E.createGame(seed);assert(E.depart(g,{seed,difficulty:'normal'}));return g;}
function encounter(g,boss=false){const entity=g.map.entities.find(e=>e.type===(boss?'boss':'enemy'));for(const [dx,dy] of E.DIRS){const p={x:entity.x-dx,y:entity.y-dy};if(g.map.tiles[p.y]?.[p.x]===1){g.pos=p;assert.equal(E.move(g,dx,dy),true);assert.equal(g.phase,'combat');return;}}throw Error('No encounter approach');}
test('900 generated floors have connected rooms, reachable distinct features, and safe entrances',()=>{for(let seed=0;seed<300;seed++)for(let floor=1;floor<=3;floor++){const m=E.generate(String(seed),floor),d=E.distances(m,m.start);assert.equal(d.size,m.tiles.flat().filter(Boolean).length);const occupied=new Set();for(const e of m.entities){const key=E.key(e.x,e.y);assert(d.has(key));assert(!occupied.has(key));occupied.add(key);const r=m.rooms[0];if(['enemy','boss'].includes(e.type))assert(!(e.x>=r.x&&e.x<r.x+r.w&&e.y>=r.y&&e.y<r.y+r.h));}assert.equal(m.entities.filter(e=>e.type==='chest').length,2);assert.equal(m.entities.filter(e=>e.type==='shrine').length,1);assert.equal(m.entities.filter(e=>e.type===(floor<3?'stairs':'boss')).length,1);}});
test('seeded generation is repeatable and seeds produce different layouts',()=>{assert.deepEqual(E.generate('moss',2),E.generate('moss',2));assert.notDeepEqual(E.generate('moss',2).tiles,E.generate('ash',2).tiles);});
test('invalid movement does not consume a turn; fog does not reveal the full map',()=>{const g=dungeonGame('a'),turn=g.turn;assert.equal(E.move(g,1,1),false);assert.equal(g.turn,turn);assert(g.map.seen.length<g.map.tiles.flat().length/2);assert.deepEqual(E.pathTo(g,38,26),[]);});
test('each hero has one action and enemies wait until the last action',()=>{const g=dungeonGame('test');encounter(g);const hp=g.party.map(h=>h.hp);assert(E.act(g,0,'guard'));assert(!E.act(g,0,'attack',0));assert.deepEqual(g.party.map(h=>h.hp),hp);assert(E.act(g,1,'guard'));assert.deepEqual(g.party.map(h=>h.hp),hp);assert(E.act(g,2,'guard'));assert.equal(g.combat.round,2);assert(g.party.some((h,i)=>h.hp<hp[i]));assert(g.party.every(h=>!h.acted));});
test('Bulwark halves damage and special abilities require a full round to recharge',()=>{const g=dungeonGame('shield');encounter(g);const before=g.party.reduce((n,h)=>n+h.hp,0),expected=g.combat.enemies.reduce((n,e)=>n+Math.ceil(e.intent.damage/2),0);assert(E.act(g,0,'special'));E.act(g,1,'guard');E.act(g,2,'guard');assert.equal(before-g.party.reduce((n,h)=>n+h.hp,0),expected);assert.equal(g.party[0].cooldown,1);assert(!E.act(g,0,'special'));E.endRound(g);assert.equal(g.party[0].cooldown,0);assert(E.act(g,0,'special'));});
test('mark enhances the next two hits, and Ember Wave damages every living enemy',()=>{const g=dungeonGame('mark');encounter(g);E.act(g,1,'special',0);const e=g.combat.enemies[0];assert.equal(e.marked,2);const hp=e.hp;E.act(g,0,'attack',0);assert.equal(hp-e.hp,Math.min(hp,Math.max(1,g.party[0].attack+3-e.armor)));assert.equal(e.marked,1);const before=g.combat.enemies.map(e=>e.hp);E.act(g,2,'special');if(g.phase==='combat')assert(g.combat.enemies.every((e,i)=>e.hp<before[i]||before[i]===0));});
test('potions reject invalid targets and heal within maximum health',()=>{const g=dungeonGame('heal'),n=g.potions;assert(!E.act(g,0,'potion',1));assert.equal(g.potions,n);g.party[1].hp-=5;assert(E.act(g,0,'potion',1));assert.equal(g.party[1].hp,g.party[1].maxHp);assert.equal(g.potions,n-1);g.party[1].hp=0;assert(!E.act(g,0,'potion',1));});
test('shrines are single use; descending revives and grants temporary resolve',()=>{const g=dungeonGame('stairs');g.party[1].hp=0;const shrine=g.map.entities.find(e=>e.type==='shrine');g.pos={x:shrine.x,y:shrine.y};assert(E.interact(g));assert.equal(g.party[1].hp,18);assert(!E.interact(g));g.party[1].hp=0;const stairs=g.map.entities.find(e=>e.type==='stairs');g.pos={x:stairs.x,y:stairs.y};const before=g.party[0].maxHp;assert(E.interact(g));assert.equal(g.floor,2);assert.equal(g.level,1);assert.equal(g.party[0].depthBonus,1);assert.equal(g.party[1].hp,12);assert.equal(g.party[0].maxHp,before+5);assert(E.validateSave(g));});
test('defeating the final guardian wins the expedition and removes encounter',()=>{const g=dungeonGame('boss');g.floor=3;g.map=E.generate(g.seed,3);encounter(g,true);const c=g.combat;c.enemies.forEach(e=>e.hp=1);assert(E.act(g,2,'special'));assert.equal(g.phase,'won');assert.equal(g.combat,null);assert(!g.map.entities.some(e=>e.type==='boss'));assert(E.validateSave(g));});
test('a party wipe is terminal and cannot move or act',()=>{const g=dungeonGame('wipe');encounter(g);g.party.forEach(h=>h.hp=1);for(let i=0;i<5&&g.phase==='combat';i++)E.endRound(g);assert.equal(g.phase,'lost');assert(!E.move(g,1,0));assert(!E.act(g,0,'potion',0));assert(E.validateSave(g));});
test('valid saves round-trip; malformed and incoherent saves are rejected',()=>{const g=dungeonGame('save');assert(E.validateSave(JSON.parse(JSON.stringify(g))));assert(!E.validateSave(null));assert(!E.validateSave({...g,phase:'nonsense'}));const dead=structuredClone(g);dead.party.forEach(h=>h.hp=0);assert(!E.validateSave(dead));encounter(g);assert(E.validateSave(g));const bad=structuredClone(g);delete bad.combat.enemies[0].attack;assert(!E.validateSave(bad));const acted=structuredClone(g);acted.party.forEach(h=>h.acted=true);assert(!E.validateSave(acted));const nan=structuredClone(g);nan.party[0].hp=NaN;assert(!E.validateSave(nan));});
test('100 deterministic battles terminate without negative health or illegal turn states',()=>{for(let i=0;i<100;i++){const g=dungeonGame('battle'+i);encounter(g);for(let j=0;j<150&&g.phase==='combat';j++){const h=g.party.findIndex(h=>h.hp>0&&!h.acted);assert(h>=0);const target=g.combat.enemies.findIndex(e=>e.hp>0);const action=g.party[h].id==='arcanist'&&!g.party[h].cooldown?'special':'attack';assert(E.act(g,h,action,target));assert(g.party.every(h=>Number.isFinite(h.hp)&&h.hp>=0&&h.hp<=h.maxHp));assert(E.validateSave(g));}assert.notEqual(g.phase,'combat');}});
